# Generated by Django 5.2.5 on 2025-08-21 12:14

import EM.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='banner',
            field=models.ImageField(storage=EM.storage_backends.OverwriteStorage(), upload_to='event_banners/'),
        ),
    ]
