# Generated by Django 5.2.5 on 2025-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_eventdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='banner',
            field=models.ImageField(upload_to='event_banners/'),
        ),
    ]
