# Generated by Django 5.2.5 on 2025-08-20 21:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_eventdetails_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='banner'),
        ),
    ]
