# Generated by Django 5.2.3 on 2025-08-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='CompanyName',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('member', 'Member')], default='member', max_length=10),
            preserve_default=False,
        ),
    ]
