# Generated by Django 5.2.5 on 2025-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetails',
            name='no_of_members',
            field=models.IntegerField(default=1),
        ),
    ]
