# Generated by Django 5.2.5 on 2025-08-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_memberdetails_no_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetails',
            name='no_of_members',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
