# Generated by Django 5.2.5 on 2025-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_memberdetails_no_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='registration_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
