# Generated by Django 5.2.5 on 2025-08-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberdetails_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetails',
            name='registration_code',
            field=models.CharField(max_length=12),
        ),
    ]
